name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout repository
        uses: action/checkout@v4
      - name: Set up Node.js
        uses: action/checkout@v4 
        with:
          node-version : '18'
      - name: install dependencies
        uses: npm install
      - name: Run Test
        uses: npm test
